version: '2'
services:
  mongo:
    image: "mongo:3.4.1"
#  rabbitmq:
#    image: "rabbitmq:3.6.6-management"
  knuckles:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
#      - rabbitmq

